// Code generated by MockGen. DO NOT EDIT.
// Source: strategy.go

// Package mocks is a generated GoMock package.
package mocks

import (
	big "math/big"
	reflect "reflect"

	fibonacci "github.com/agbru/fibcalc/internal/fibonacci"
	gomock "github.com/golang/mock/gomock"
)

// MockMultiplicationStrategy is a mock of MultiplicationStrategy interface.
type MockMultiplicationStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockMultiplicationStrategyMockRecorder
}

// MockMultiplicationStrategyMockRecorder is the mock recorder for MockMultiplicationStrategy.
type MockMultiplicationStrategyMockRecorder struct {
	mock *MockMultiplicationStrategy
}

// NewMockMultiplicationStrategy creates a new mock instance.
func NewMockMultiplicationStrategy(ctrl *gomock.Controller) *MockMultiplicationStrategy {
	mock := &MockMultiplicationStrategy{ctrl: ctrl}
	mock.recorder = &MockMultiplicationStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMultiplicationStrategy) EXPECT() *MockMultiplicationStrategyMockRecorder {
	return m.recorder
}

// ExecuteStep mocks base method.
func (m *MockMultiplicationStrategy) ExecuteStep(s *fibonacci.CalculationState, opts fibonacci.Options, inParallel bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStep", s, opts, inParallel)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteStep indicates an expected call of ExecuteStep.
func (mr *MockMultiplicationStrategyMockRecorder) ExecuteStep(s, opts, inParallel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStep", reflect.TypeOf((*MockMultiplicationStrategy)(nil).ExecuteStep), s, opts, inParallel)
}

// Multiply mocks base method.
func (m *MockMultiplicationStrategy) Multiply(z, x, y *big.Int, opts fibonacci.Options) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Multiply", z, x, y, opts)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Multiply indicates an expected call of Multiply.
func (mr *MockMultiplicationStrategyMockRecorder) Multiply(z, x, y, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Multiply", reflect.TypeOf((*MockMultiplicationStrategy)(nil).Multiply), z, x, y, opts)
}

// Name mocks base method.
func (m *MockMultiplicationStrategy) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMultiplicationStrategyMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMultiplicationStrategy)(nil).Name))
}

// Square mocks base method.
func (m *MockMultiplicationStrategy) Square(z, x *big.Int, opts fibonacci.Options) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Square", z, x, opts)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Square indicates an expected call of Square.
func (mr *MockMultiplicationStrategyMockRecorder) Square(z, x, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Square", reflect.TypeOf((*MockMultiplicationStrategy)(nil).Square), z, x, opts)
}
