// Code generated by MockGen. DO NOT EDIT.
// Source: calculator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	fibonacci "github.com/agbru/fibcalc/internal/fibonacci"
	gomock "github.com/golang/mock/gomock"
)

// MockCalculator is a mock of Calculator interface.
type MockCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockCalculatorMockRecorder
}

// MockCalculatorMockRecorder is the mock recorder for MockCalculator.
type MockCalculatorMockRecorder struct {
	mock *MockCalculator
}

// NewMockCalculator creates a new mock instance.
func NewMockCalculator(ctrl *gomock.Controller) *MockCalculator {
	mock := &MockCalculator{ctrl: ctrl}
	mock.recorder = &MockCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculator) EXPECT() *MockCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockCalculator) Calculate(ctx context.Context, progressChan chan<- fibonacci.ProgressUpdate, calcIndex int, n uint64, opts fibonacci.Options) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", ctx, progressChan, calcIndex, n, opts)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calculate indicates an expected call of Calculate.
func (mr *MockCalculatorMockRecorder) Calculate(ctx, progressChan, calcIndex, n, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockCalculator)(nil).Calculate), ctx, progressChan, calcIndex, n, opts)
}

// Name mocks base method.
func (m *MockCalculator) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCalculatorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCalculator)(nil).Name))
}

// MockcoreCalculator is a mock of coreCalculator interface.
type MockcoreCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockcoreCalculatorMockRecorder
}

// MockcoreCalculatorMockRecorder is the mock recorder for MockcoreCalculator.
type MockcoreCalculatorMockRecorder struct {
	mock *MockcoreCalculator
}

// NewMockcoreCalculator creates a new mock instance.
func NewMockcoreCalculator(ctrl *gomock.Controller) *MockcoreCalculator {
	mock := &MockcoreCalculator{ctrl: ctrl}
	mock.recorder = &MockcoreCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcoreCalculator) EXPECT() *MockcoreCalculatorMockRecorder {
	return m.recorder
}

// CalculateCore mocks base method.
func (m *MockcoreCalculator) CalculateCore(ctx context.Context, reporter fibonacci.ProgressReporter, n uint64, opts fibonacci.Options) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateCore", ctx, reporter, n, opts)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateCore indicates an expected call of CalculateCore.
func (mr *MockcoreCalculatorMockRecorder) CalculateCore(ctx, reporter, n, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateCore", reflect.TypeOf((*MockcoreCalculator)(nil).CalculateCore), ctx, reporter, n, opts)
}

// Name mocks base method.
func (m *MockcoreCalculator) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockcoreCalculatorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockcoreCalculator)(nil).Name))
}
