package calibration

import (
	"context"
	"io"
	"math/big"
	"testing"
	"time"

	"github.com/agbru/fibcalc/internal/config"
	"github.com/agbru/fibcalc/internal/fibonacci"
)

// MockCalculator implements fibonacci.Calculator for testing calibration
type MockCalculator struct {
	name string
}

func (m *MockCalculator) Name() string {
	return m.name
}

func (m *MockCalculator) Calculate(ctx context.Context, progressChan chan<- fibonacci.ProgressUpdate, calcIndex int, n uint64, opts fibonacci.Options) (*big.Int, error) {
	// Simulate work duration dependent on threshold to test optimization logic
	// In findBestParallelThreshold, we test various candidates.
	// We want one to be faster than others.

	duration := 10 * time.Millisecond

	// Simulate simpler logic: specific threshold yields faster time
	if opts.ParallelThreshold == 4096 {
		duration = 1 * time.Millisecond
	}

	// Respect context timeout/cancellation
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	case <-time.After(duration):
	}

	return big.NewInt(1), nil
}

func TestAutoCalibrate(t *testing.T) {
	// Mock registry
	registry := map[string]fibonacci.Calculator{
		"fast":   &MockCalculator{name: "fast"},
		"matrix": &MockCalculator{name: "matrix"},
	}

	cfg := config.AppConfig{
		Timeout: 1 * time.Second, // Short timeout for test
		CalibrationProfile: "", // Don't use file
	}

	// We need to avoid loading real profiles during test, or ensure tmp path
	// The function LoadCachedCalibration uses LoadOrCreateProfile which might touch FS.
	// Best to use a temp file for profile path.
	tmpProfile := t.TempDir() + "/profile.json"
	cfg.CalibrationProfile = tmpProfile

	ctx := context.Background()

	// Run AutoCalibrate
	// It will run trials. Our mock sleeps.
	updatedCfg, success := AutoCalibrate(ctx, cfg, io.Discard, registry)

	if !success {
		t.Error("AutoCalibrate should succeed with mock calculator")
	}

	// Check if thresholds are updated (Mock logic makes 4096 fastest if generated in candidates)
	// Default candidates are generated by GenerateQuickParallelThresholds.
	// If 4096 is in candidates, it should be picked.
	// (Note: GenerateQuickParallelThresholds logic is internal but we assume standard values)

	if updatedCfg.Threshold == 0 {
		t.Error("Threshold should be set")
	}
}

func TestRunCalibration(t *testing.T) {
	registry := map[string]fibonacci.Calculator{
		"fast": &MockCalculator{name: "fast"},
	}

	ctx := context.Background()
	exitCode := RunCalibration(ctx, io.Discard, registry)

	if exitCode != 0 { // ExitSuccess
		t.Errorf("RunCalibration failed with code %d", exitCode)
	}
}

func TestRunCalibrationMissingFast(t *testing.T) {
	registry := map[string]fibonacci.Calculator{} // Empty

	ctx := context.Background()
	exitCode := RunCalibration(ctx, io.Discard, registry)

	if exitCode == 0 {
		t.Error("RunCalibration should fail if 'fast' calculator is missing")
	}
}

func TestLoadCachedCalibration(t *testing.T) {
	// Test failure first
	cfg := config.AppConfig{}
	_, success := LoadCachedCalibration(cfg, "nonexistent.json")
	if success {
		t.Error("Should return false for nonexistent profile")
	}
}
