package calibration

import (
	"bytes"
	"context"
	"io"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/agbruneau/FibGo/internal/config"
	apperrors "github.com/agbruneau/FibGo/internal/errors"
	"github.com/agbruneau/FibGo/internal/fibonacci"
	"github.com/agbruneau/FibGo/internal/progress"
)

// noopProgressDisplay drains the progress channel without output (for tests).
func noopProgressDisplay(wg *sync.WaitGroup, progressChan <-chan progress.ProgressUpdate, _ int, _ io.Writer) {
	defer wg.Done()
	for range progressChan {
	}
}

// noopColorProvider returns empty strings for all colors (for tests).
type noopColorProvider struct{}

var _ apperrors.ColorProvider = noopColorProvider{}

func (noopColorProvider) Red() string    { return "" }
func (noopColorProvider) Yellow() string { return "" }
func (noopColorProvider) Reset() string  { return "" }

// MockCalculator implements fibonacci.Calculator for testing calibration
type MockCalculator struct {
	name string
}

func (m *MockCalculator) Name() string {
	return m.name
}

func (m *MockCalculator) Calculate(ctx context.Context, progressChan chan<- progress.ProgressUpdate, calcIndex int, n uint64, opts fibonacci.Options) (*big.Int, error) {
	// Simulate work duration dependent on threshold to test optimization logic
	// We use cumulative speedups to ensure the combination of optimal parameters
	// yields the strictly fastest time.

	// Base duration
	duration := 100 * time.Millisecond

	// Parallel speedup
	// We accept a range of values (2048-8192) to match adaptive environment logic
	if opts.ParallelThreshold >= 2048 && opts.ParallelThreshold <= 8192 {
		duration -= 40 * time.Millisecond
	}

	// FFT speedup
	if opts.FFTThreshold >= 750000 && opts.FFTThreshold <= 1000000 {
		duration -= 20 * time.Millisecond
	}

	// Strassen speedup
	if opts.StrassenThreshold >= 192 && opts.StrassenThreshold <= 512 {
		duration -= 20 * time.Millisecond
	}

	// Respect context timeout/cancellation
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	case <-time.After(duration):
	}

	return big.NewInt(1), nil
}

func TestAutoCalibrate(t *testing.T) {
	t.Parallel()
	// Mock registry
	registry := map[string]fibonacci.Calculator{
		"fast":   &MockCalculator{name: "fast"},
		"matrix": &MockCalculator{name: "matrix"},
	}

	cfg := config.AppConfig{
		Timeout:            1 * time.Second, // Short timeout for test
		CalibrationProfile: "",              // Don't use file
	}

	// We need to avoid loading real profiles during test, or ensure tmp path
	// The function LoadCachedCalibration uses LoadOrCreateProfile which might touch FS.
	// Best to use a temp file for profile path.
	tmpProfile := t.TempDir() + "/profile.json"
	cfg.CalibrationProfile = tmpProfile

	ctx := context.Background()

	// Run AutoCalibrate
	// It will run trials. Our mock sleeps.
	updatedCfg, success := AutoCalibrate(ctx, cfg, io.Discard, registry)

	if !success {
		t.Error("AutoCalibrate should succeed with mock calculator")
	}

	// Check if thresholds are updated (Mock logic makes 4096 fastest if generated in candidates)
	// Default candidates are generated by GenerateQuickParallelThresholds.
	// If 4096 is in candidates, it should be picked.
	// (Note: GenerateQuickParallelThresholds logic is internal but we assume standard values)

	if updatedCfg.Threshold == 0 {
		t.Error("Threshold should be set")
	}
}

func TestRunCalibration(t *testing.T) {
	t.Parallel()
	registry := map[string]fibonacci.Calculator{
		"fast": &MockCalculator{name: "fast"},
	}

	ctx := context.Background()
	exitCode := RunCalibration(ctx, io.Discard, registry, filepath.Join(t.TempDir(), "profile.json"), noopProgressDisplay, noopColorProvider{})

	if exitCode != 0 { // ExitSuccess
		t.Errorf("RunCalibration failed with code %d", exitCode)
	}
}

// TestRunCalibration_HonorsCustomProfilePath pins the --calibration-profile
// wiring for the full -calibrate mode (audit Fable5 CAL-01): the profile must
// be saved at the caller-provided path, not the default one.
func TestRunCalibration_HonorsCustomProfilePath(t *testing.T) {
	t.Parallel()
	registry := map[string]fibonacci.Calculator{
		"fast": &MockCalculator{name: "fast"},
	}
	profilePath := filepath.Join(t.TempDir(), "cal.json")

	exitCode := RunCalibration(context.Background(), io.Discard, registry, profilePath, noopProgressDisplay, noopColorProvider{})

	if exitCode != 0 {
		t.Fatalf("RunCalibration failed with code %d", exitCode)
	}
	if _, err := os.Stat(profilePath); err != nil {
		t.Fatalf("profile was not saved at the custom path: %v", err)
	}
}

func TestRunCalibrationMissingFast(t *testing.T) {
	t.Parallel()
	registry := map[string]fibonacci.Calculator{} // Empty

	ctx := context.Background()
	exitCode := RunCalibration(ctx, io.Discard, registry, filepath.Join(t.TempDir(), "profile.json"), noopProgressDisplay, noopColorProvider{})

	if exitCode == 0 {
		t.Error("RunCalibration should fail if 'fast' calculator is missing")
	}
}

func TestLoadCachedCalibration(t *testing.T) {
	t.Parallel()

	t.Run("Nonexistent profile", func(t *testing.T) {
		t.Parallel()
		cfg := config.AppConfig{}
		_, success := LoadCachedCalibration(cfg, "nonexistent.json")
		if success {
			t.Error("Should return false for nonexistent profile")
		}
	})

	t.Run("Valid profile loaded", func(t *testing.T) {
		t.Parallel()
		tmpDir := t.TempDir()
		profilePath := tmpDir + "/profile.json"

		// Create a valid profile
		profile := NewProfile()
		profile.OptimalParallelThreshold = 4096
		profile.OptimalFFTThreshold = 1000000
		profile.OptimalStrassenThreshold = 256
		if err := profile.SaveProfile(profilePath); err != nil {
			t.Fatalf("Failed to save profile: %v", err)
		}

		cfg := config.AppConfig{
			Threshold:         2048,
			FFTThreshold:      500000,
			StrassenThreshold: 512,
		}

		updated, success := LoadCachedCalibration(cfg, profilePath)
		if !success {
			t.Error("Should return true for valid profile")
		}
		if updated.Threshold != 4096 {
			t.Errorf("Threshold = %d, want 4096", updated.Threshold)
		}
		if updated.FFTThreshold != 1000000 {
			t.Errorf("FFTThreshold = %d, want 1000000", updated.FFTThreshold)
		}
		if updated.StrassenThreshold != 256 {
			t.Errorf("StrassenThreshold = %d, want 256", updated.StrassenThreshold)
		}
	})

	t.Run("Invalid profile", func(t *testing.T) {
		t.Parallel()
		tmpDir := t.TempDir()
		profilePath := tmpDir + "/invalid.json"

		// Create an invalid profile (empty file)
		if err := os.WriteFile(profilePath, []byte("{}"), 0600); err != nil {
			t.Fatalf("Failed to write invalid profile: %v", err)
		}

		cfg := config.AppConfig{}
		_, success := LoadCachedCalibration(cfg, profilePath)
		if success {
			t.Error("Should return false for invalid profile")
		}
	})
}

func TestAutoCalibrateWithProfile(t *testing.T) {
	t.Parallel()

	t.Run("Load existing profile", func(t *testing.T) {
		t.Parallel()
		tmpDir := t.TempDir()
		profilePath := tmpDir + "/profile.json"

		// Create a valid profile
		profile := NewProfile()
		profile.OptimalParallelThreshold = 4096
		profile.OptimalFFTThreshold = 1000000
		profile.OptimalStrassenThreshold = 256
		if err := profile.SaveProfile(profilePath); err != nil {
			t.Fatalf("Failed to save profile: %v", err)
		}

		registry := map[string]fibonacci.Calculator{
			"fast": &MockCalculator{name: "fast"},
		}

		cfg := config.AppConfig{
			Timeout: 1 * time.Second,
		}

		var outBuf bytes.Buffer
		ctx := context.Background()
		updated, ok := AutoCalibrateWithProfile(ctx, cfg, &outBuf, registry, profilePath)

		if !ok {
			t.Error("AutoCalibrateWithProfile should succeed with existing profile")
		}
		if updated.Threshold != 4096 {
			t.Errorf("Threshold = %d, want 4096", updated.Threshold)
		}
		output := outBuf.String()
		if !strings.Contains(output, "Using cached calibration") {
			t.Errorf("Output should mention cached calibration. Got: %s", output)
		}
	})

	// SEC-01: the runtime auto-calibrate path must not trust a hardware-valid
	// but forged on-disk profile whose thresholds are out of range. IsValid()
	// checks hardware compatibility only, so a negative threshold would leak
	// straight into the running config via applyCachedProfile.
	t.Run("Forged fresh profile with negative threshold is not applied", func(t *testing.T) {
		t.Parallel()
		tmpDir := t.TempDir()
		profilePath := tmpDir + "/forged.json"

		// NewProfile() stamps the current hardware fields, so IsValid() passes;
		// CalibratedAt is now, so it is fresh (not stale). Only the threshold
		// is forged.
		profile := NewProfile()
		profile.OptimalParallelThreshold = -1
		profile.OptimalFFTThreshold = 600000
		profile.OptimalStrassenThreshold = 4096
		if err := profile.SaveProfile(profilePath); err != nil {
			t.Fatalf("Failed to save forged profile: %v", err)
		}

		registry := map[string]fibonacci.Calculator{
			"fast": &MockCalculator{name: "fast"},
		}
		cfg := config.AppConfig{Timeout: 5 * time.Second}

		var outBuf bytes.Buffer
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		updated, _ := AutoCalibrateWithProfile(ctx, cfg, &outBuf, registry, profilePath)

		if updated.Threshold < 0 {
			t.Fatalf("forged negative threshold leaked via auto-calibrate: Threshold=%d", updated.Threshold)
		}
		if strings.Contains(outBuf.String(), "Using cached calibration") {
			t.Errorf("forged profile must not be applied as a cached calibration; output=%q", outBuf.String())
		}
	})

	t.Run("Quick calibration fallback", func(t *testing.T) {
		t.Parallel()
		tmpDir := t.TempDir()
		profilePath := tmpDir + "/profile.json"

		registry := map[string]fibonacci.Calculator{
			"fast": &MockCalculator{name: "fast"},
		}

		cfg := config.AppConfig{
			Timeout: 5 * time.Second,
		}

		var outBuf bytes.Buffer
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		defer cancel()

		updated, ok := AutoCalibrateWithProfile(ctx, cfg, &outBuf, registry, profilePath)

		// Quick calibration may succeed or timeout
		if ok {
			if updated.Threshold == 0 {
				t.Error("Threshold should be set after quick calibration")
			}
			output := outBuf.String()
			if !strings.Contains(output, "Quick calibration") && !strings.Contains(output, "calibration") {
				t.Errorf("Output should mention calibration. Got: %s", output)
			}
		}
	})

	t.Run("Full calibration fallback", func(t *testing.T) {
		t.Parallel()
		tmpDir := t.TempDir()
		profilePath := tmpDir + "/profile.json"

		registry := map[string]fibonacci.Calculator{
			"fast":   &MockCalculator{name: "fast"},
			"matrix": &MockCalculator{name: "matrix"},
		}

		cfg := config.AppConfig{
			Timeout: 5 * time.Second,
		}

		var outBuf bytes.Buffer
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()

		updated, ok := AutoCalibrateWithProfile(ctx, cfg, &outBuf, registry, profilePath)

		// Full calibration may succeed or timeout
		if ok {
			if updated.Threshold == 0 {
				t.Error("Threshold should be set after full calibration")
			}
		}
	})

	t.Run("Failed auto-calibration warns the user", func(t *testing.T) {
		t.Parallel()
		registry := map[string]fibonacci.Calculator{
			"fast": &MockCalculator{name: "fast"},
		}
		ctx, cancel := context.WithCancel(context.Background())
		cancel() // every strategy fails on the dead context

		var outBuf bytes.Buffer
		updated, ok := AutoCalibrateWithProfile(ctx, config.AppConfig{Threshold: 1234}, &outBuf, registry, filepath.Join(t.TempDir(), "p.json"))

		if ok {
			t.Fatal("expected auto-calibration to fail on a canceled context")
		}
		if updated.Threshold != 1234 {
			t.Errorf("config must be returned unchanged on failure, got Threshold=%d", updated.Threshold)
		}
		// ERR-05: the user explicitly asked for --auto-calibrate; a silent
		// fallback to defaults leaves them believing calibration happened.
		if !strings.Contains(outBuf.String(), "auto-calibration failed") {
			t.Errorf("failure must warn the user; output=%q", outBuf.String())
		}
	})

	t.Run("No fast calculator", func(t *testing.T) {
		t.Parallel()
		tmpDir := t.TempDir()
		profilePath := tmpDir + "/profile.json"

		registry := map[string]fibonacci.Calculator{} // Empty

		cfg := config.AppConfig{
			Timeout:   1 * time.Second,
			Threshold: 0, // Explicitly set to 0
		}

		var outBuf bytes.Buffer
		ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
		defer cancel()

		updated, ok := AutoCalibrateWithProfile(ctx, cfg, &outBuf, registry, profilePath)

		// QuickCalibrate might succeed even without fast calculator (it uses bigfft directly)
		// So we check that if it fails, the config remains unchanged
		if !ok {
			if updated.Threshold != cfg.Threshold {
				t.Errorf("Config should remain unchanged on failure. Threshold = %d, want %d",
					updated.Threshold, cfg.Threshold)
			}
		} else {
			// If it succeeded (via QuickCalibrate), thresholds should be set
			if updated.Threshold == 0 {
				t.Error("If calibration succeeded, threshold should be set")
			}
		}
	})
}

func TestCalibrationRunner(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	runner := newCalibrationRunner(ctx, 1*time.Second)
	calc := &MockCalculator{name: "fast"}

	// Test findBestParallelThreshold
	bestPar, parDur := runner.findBestParallelThreshold(calc, 4096)
	if bestPar == 0 {
		t.Error("findBestParallelThreshold should return a non-zero threshold")
	}
	if parDur == 0 {
		t.Error("findBestParallelThreshold should return a non-zero duration")
	}

	// Test findBestFFTThreshold
	bestFFT, fftDur := runner.findBestFFTThreshold(calc, bestPar, 1000000)
	if bestFFT == 0 {
		t.Error("findBestFFTThreshold should return a non-zero threshold")
	}
	if fftDur == 0 {
		t.Error("findBestFFTThreshold should return a non-zero duration")
	}

	// Test findBestStrassenThreshold
	bestStr, strDur := runner.findBestStrassenThreshold(calc, bestPar, 256)
	if bestStr == 0 {
		t.Error("findBestStrassenThreshold should return a non-zero threshold")
	}
	if strDur == 0 {
		t.Error("findBestStrassenThreshold should return a non-zero duration")
	}
}

func TestProfileMaxAgeFromEnv(t *testing.T) {
	// Not parallel: mutates process-wide environment variable.

	t.Run("Unset returns default", func(t *testing.T) {
		t.Setenv(ProfileMaxAgeEnv, "")
		if got := profileMaxAgeFromEnv(); got != DefaultProfileMaxAge {
			t.Errorf("profileMaxAgeFromEnv() = %v, want %v", got, DefaultProfileMaxAge)
		}
	})

	t.Run("Valid override is honored", func(t *testing.T) {
		t.Setenv(ProfileMaxAgeEnv, "30m")
		if got := profileMaxAgeFromEnv(); got != 30*time.Minute {
			t.Errorf("profileMaxAgeFromEnv() = %v, want 30m", got)
		}
	})

	t.Run("Invalid value falls back to default", func(t *testing.T) {
		t.Setenv(ProfileMaxAgeEnv, "not-a-duration")
		if got := profileMaxAgeFromEnv(); got != DefaultProfileMaxAge {
			t.Errorf("profileMaxAgeFromEnv() = %v, want %v", got, DefaultProfileMaxAge)
		}
	})

	t.Run("Non-positive value falls back to default", func(t *testing.T) {
		t.Setenv(ProfileMaxAgeEnv, "0s")
		if got := profileMaxAgeFromEnv(); got != DefaultProfileMaxAge {
			t.Errorf("profileMaxAgeFromEnv() = %v, want %v", got, DefaultProfileMaxAge)
		}
	})
}

func TestAutoCalibrateWithProfile_StaleProfileTriggersRecalibration(t *testing.T) {
	// Not parallel: t.Setenv pins this test to a single goroutine.
	tmpDir := t.TempDir()
	profilePath := tmpDir + "/profile.json"

	// Build a profile that is hardware-valid (NewProfile populates current
	// hardware fields) but predates the freshness window by two weeks.
	profile := NewProfile()
	profile.OptimalParallelThreshold = 4096
	profile.OptimalFFTThreshold = 1000000
	profile.OptimalStrassenThreshold = 256
	profile.Confidence = 1.0
	profile.CalibratedAt = time.Now().Add(-14 * 24 * time.Hour)

	// Sanity: IsValid stays true (hardware match), IsStale must report true
	// against any reasonable max-age (default = 7 days).
	if !profile.IsValid() {
		t.Fatalf("precondition failed: profile should be valid for current hardware")
	}
	if !profile.IsStale(DefaultProfileMaxAge) {
		t.Fatalf("precondition failed: 14-day-old profile should be stale vs default max age")
	}

	if err := profile.SaveProfile(profilePath); err != nil {
		t.Fatalf("Failed to save profile: %v", err)
	}

	// Force the default max-age (7d) regardless of caller environment.
	t.Setenv(ProfileMaxAgeEnv, "")

	registry := map[string]fibonacci.Calculator{
		"fast":   &MockCalculator{name: "fast"},
		"matrix": &MockCalculator{name: "matrix"},
	}

	cfg := config.AppConfig{
		Timeout: 5 * time.Second,
	}

	var outBuf bytes.Buffer
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	updated, ok := AutoCalibrateWithProfile(ctx, cfg, &outBuf, registry, profilePath)
	if !ok {
		t.Fatalf("AutoCalibrateWithProfile should succeed; output=%q", outBuf.String())
	}

	output := outBuf.String()
	if !strings.Contains(output, "Profile stale") {
		t.Errorf("Output should mention stale profile re-calibration. Got: %s", output)
	}
	if !strings.Contains(output, "re-calibrating") {
		t.Errorf("Output should mention re-calibrating. Got: %s", output)
	}
	if strings.Contains(output, "Using cached calibration") {
		t.Errorf("Output should NOT advertise cached calibration when profile is stale. Got: %s", output)
	}
	if strings.Contains(output, "Quick calibration") {
		t.Errorf("Stale profile must skip the quick path and run full calibration. Got: %s", output)
	}

	// The full calibration path must overwrite the on-disk profile with a
	// fresh CalibratedAt timestamp; verify the persisted profile is no
	// longer stale.
	reloaded, reloadedOK := LoadOrCreateProfile(profilePath)
	if !reloadedOK {
		t.Fatalf("Reloaded profile should be valid after re-calibration")
	}
	if reloaded.IsStale(DefaultProfileMaxAge) {
		t.Errorf("Profile persisted after re-calibration should not be stale; CalibratedAt=%s", reloaded.CalibratedAt)
	}
	if updated.Threshold == 0 {
		t.Errorf("Re-calibrated config should have a non-zero parallel threshold")
	}
}

// TestTryFastThenEscalate_InvalidMeasurementsEscalates is the FIB-03 guard
// test: with a pre-canceled context, FastStrategy.Calibrate cannot collect
// any timing (runParallelTests returns no results), so analyzeResults must
// report confidence 0 and tryFastThenEscalate must signal escalation
// (ok=false) rather than accepting an inflated fallback confidence. Before
// the fix, the >0 defaults in find*Crossover added +0.2/+0.2 bonuses even
// with zero real data, making escalation unreachable via this path.
func TestTryFastThenEscalate_InvalidMeasurementsEscalates(t *testing.T) {
	t.Parallel()

	ctx, cancel := context.WithCancel(context.Background())
	cancel() // pre-canceled: no measurement can complete

	stratOpts := StrategyOptions{
		BaseConfig: config.AppConfig{StrassenThreshold: 256},
		Out:        io.Discard,
	}

	_, ok := tryFastThenEscalate(ctx, stratOpts, "")
	if ok {
		t.Error("tryFastThenEscalate should signal escalation (ok=false) when no valid measurement was collected")
	}
}

func TestApplyCalibrationResults(t *testing.T) {
	t.Parallel()
	cfg := config.AppConfig{}
	updated, ok := applyCalibrationResults(cfg, 4096, 10*time.Millisecond, 1000000, 10*time.Millisecond, 256, 10*time.Millisecond)
	if !ok {
		t.Error("applyCalibrationResults should return true")
	}
	if updated.Threshold != 4096 {
		t.Errorf("Threshold = %d, want 4096", updated.Threshold)
	}
}
