// Code generated by MockGen. DO NOT EDIT.
// Source: ui.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSpinner is a mock of Spinner interface.
type MockSpinner struct {
	ctrl     *gomock.Controller
	recorder *MockSpinnerMockRecorder
}

// MockSpinnerMockRecorder is the mock recorder for MockSpinner.
type MockSpinnerMockRecorder struct {
	mock *MockSpinner
}

// NewMockSpinner creates a new mock instance.
func NewMockSpinner(ctrl *gomock.Controller) *MockSpinner {
	mock := &MockSpinner{ctrl: ctrl}
	mock.recorder = &MockSpinnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpinner) EXPECT() *MockSpinnerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockSpinner) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockSpinnerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSpinner)(nil).Start))
}

// Stop mocks base method.
func (m *MockSpinner) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockSpinnerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSpinner)(nil).Stop))
}

// UpdateSuffix mocks base method.
func (m *MockSpinner) UpdateSuffix(suffix string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateSuffix", suffix)
}

// UpdateSuffix indicates an expected call of UpdateSuffix.
func (mr *MockSpinnerMockRecorder) UpdateSuffix(suffix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSuffix", reflect.TypeOf((*MockSpinner)(nil).UpdateSuffix), suffix)
}
