// Code generated by MockGen. DO NOT EDIT.
// Source: generator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSequenceGenerator is a mock of SequenceGenerator interface.
type MockSequenceGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSequenceGeneratorMockRecorder
}

// MockSequenceGeneratorMockRecorder is the mock recorder for MockSequenceGenerator.
type MockSequenceGeneratorMockRecorder struct {
	mock *MockSequenceGenerator
}

// NewMockSequenceGenerator creates a new mock instance.
func NewMockSequenceGenerator(ctrl *gomock.Controller) *MockSequenceGenerator {
	mock := &MockSequenceGenerator{ctrl: ctrl}
	mock.recorder = &MockSequenceGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSequenceGenerator) EXPECT() *MockSequenceGeneratorMockRecorder {
	return m.recorder
}

// Current mocks base method.
func (m *MockSequenceGenerator) Current() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// Current indicates an expected call of Current.
func (mr *MockSequenceGeneratorMockRecorder) Current() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockSequenceGenerator)(nil).Current))
}

// Index mocks base method.
func (m *MockSequenceGenerator) Index() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockSequenceGeneratorMockRecorder) Index() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockSequenceGenerator)(nil).Index))
}

// Next mocks base method.
func (m *MockSequenceGenerator) Next(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockSequenceGeneratorMockRecorder) Next(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockSequenceGenerator)(nil).Next), ctx)
}

// Reset mocks base method.
func (m *MockSequenceGenerator) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockSequenceGeneratorMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockSequenceGenerator)(nil).Reset))
}

// Skip mocks base method.
func (m *MockSequenceGenerator) Skip(ctx context.Context, n uint64) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Skip", ctx, n)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Skip indicates an expected call of Skip.
func (mr *MockSequenceGeneratorMockRecorder) Skip(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Skip", reflect.TypeOf((*MockSequenceGenerator)(nil).Skip), ctx, n)
}
